export const productsFromCountdown = [
  {
    products: {
      items: [
        {
          type: "Product",
          name: "countdown milk standard",
          barcode: "9414742036509",
          variety: "standard",
          brand: "countdown",
          slug: "countdown-milk-standard",
          sku: "282768",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 5.42,
            salePrice: 5.42,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282768.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282768.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 1.81,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "3L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "Other",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: {
              name: "Countdown's Own",
              link: "/shop/productgroup/80842",
              imagePath: "/Content/PromotionTags/F18-Core-Tag.png",
              linkTarget: "_self",
              altText: null,
            },
            targetedOffer: null,
          },
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk standard",
          barcode: "9414742036455",
          variety: "standard",
          brand: "countdown",
          slug: "countdown-milk-standard",
          sku: "282765",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 3.63,
            salePrice: 3.63,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282765.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282765.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 1.82,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "2L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "Other",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: {
              name: "Countdown's Own",
              link: "/shop/productgroup/80842",
              imagePath: "/Content/PromotionTags/F18-Core-Tag.png",
              linkTarget: "_self",
              altText: null,
            },
            targetedOffer: null,
          },
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk lite",
          barcode: "9414742036516",
          variety: "lite",
          brand: "countdown",
          slug: "countdown-milk-lite",
          sku: "282769",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 5.42,
            salePrice: 5.42,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282769.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282769.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 1.81,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "3L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "Other",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: {
              name: "Countdown's Own",
              link: "/shop/productgroup/80842",
              imagePath: "/Content/PromotionTags/F18-Core-Tag.png",
              linkTarget: "_self",
              altText: null,
            },
            targetedOffer: null,
          },
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk standard uht",
          barcode: "9400597021999",
          variety: "standard uht",
          brand: "countdown",
          slug: "countdown-milk-standard-uht",
          sku: "596964",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 2.5,
            salePrice: 2.2,
            savePrice: 0.3,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: true,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/596964.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/596964.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 0.22,
            cupMeasure: "100mL",
            packageType: "carton",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "IsSpecial",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: null,
            targetedOffer: null,
          },
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk lite",
          barcode: "9414742036462",
          variety: "lite",
          brand: "countdown",
          slug: "countdown-milk-lite",
          sku: "282766",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 3.63,
            salePrice: 3.63,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282766.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282766.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 1.82,
            cupMeasure: "1L",
            packageType: null,
            volumeSize: "2L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "Other",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: {
              name: "Countdown's Own",
              link: "/shop/productgroup/80842",
              imagePath: "/Content/PromotionTags/F18-Core-Tag.png",
              linkTarget: "_self",
              altText: null,
            },
            targetedOffer: null,
          },
          departments: [
            {
              id: 16,
              name: "Christmas",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk standard",
          barcode: "9414742036417",
          variety: "standard",
          brand: "countdown",
          slug: "countdown-milk-standard",
          sku: "282764",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 2.43,
            salePrice: 2.43,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282764.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282764.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 2.43,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "Other",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: {
              name: "Countdown's Own",
              link: "/shop/productgroup/80842",
              imagePath: "/Content/PromotionTags/F18-Core-Tag.png",
              linkTarget: "_self",
              altText: null,
            },
            targetedOffer: null,
          },
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk trim",
          barcode: "9414742036714",
          variety: "trim",
          brand: "countdown",
          slug: "countdown-milk-trim",
          sku: "282767",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 3.63,
            salePrice: 3.63,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282767.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282767.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 1.82,
            cupMeasure: "1L",
            packageType: null,
            volumeSize: "2L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "Other",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: {
              name: "Countdown's Own",
              link: "/shop/productgroup/80842",
              imagePath: "/Content/PromotionTags/F18-Core-Tag.png",
              linkTarget: "_self",
              altText: null,
            },
            targetedOffer: null,
          },
          departments: [
            {
              id: 16,
              name: "Christmas",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk lite",
          barcode: "9414742036424",
          variety: "lite",
          brand: "countdown",
          slug: "countdown-milk-lite",
          sku: "282772",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 2.43,
            salePrice: 2.43,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282772.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282772.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 2.43,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "Other",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: {
              name: "Countdown's Own",
              link: "/shop/productgroup/80842",
              imagePath: "/Content/PromotionTags/F18-Core-Tag.png",
              linkTarget: "_self",
              altText: null,
            },
            targetedOffer: null,
          },
          departments: [
            {
              id: 16,
              name: "Christmas",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk lite uht",
          barcode: "9400597022002",
          variety: "lite uht",
          brand: "countdown",
          slug: "countdown-milk-lite-uht",
          sku: "596966",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 2.5,
            salePrice: 2.2,
            savePrice: 0.3,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: true,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/596966.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/596966.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 0.22,
            cupMeasure: "100mL",
            packageType: "carton",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "IsSpecial",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: null,
            targetedOffer: null,
          },
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk trim",
          barcode: "9414742036431",
          variety: "trim",
          brand: "countdown",
          slug: "countdown-milk-trim",
          sku: "282780",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 2.43,
            salePrice: 2.43,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282780.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282780.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 2.43,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "Other",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: {
              name: "Countdown's Own",
              link: "/shop/productgroup/80842",
              imagePath: "/Content/PromotionTags/F18-Core-Tag.png",
              linkTarget: "_self",
              altText: null,
            },
            targetedOffer: null,
          },
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk trim",
          barcode: "9414742036523",
          variety: "trim",
          brand: "countdown",
          slug: "countdown-milk-trim",
          sku: "282773",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 5.42,
            salePrice: 5.42,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282773.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282773.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 1.81,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "3L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "Other",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: {
              name: "Countdown's Own",
              link: "/shop/productgroup/80842",
              imagePath: "/Content/PromotionTags/F18-Core-Tag.png",
              linkTarget: "_self",
              altText: null,
            },
            targetedOffer: null,
          },
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk trim uht",
          barcode: "9400597022019",
          variety: "trim uht",
          brand: "countdown",
          slug: "countdown-milk-trim-uht",
          sku: "596967",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 2.5,
            salePrice: 2.2,
            savePrice: 0.3,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: true,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/596967.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/596967.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 0.22,
            cupMeasure: "100mL",
            packageType: "carton",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "IsSpecial",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: null,
            targetedOffer: null,
          },
          departments: [
            {
              id: 7,
              name: "Pantry",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "anchor milk standard blue",
          barcode: "94152210",
          variety: "standard blue",
          brand: "anchor",
          slug: "anchor-milk-standard-blue",
          sku: "282819",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 4.92,
            salePrice: 4.92,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282819.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282819.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 2.46,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "2L",
          },
          hasShopperNotes: null,
          productTag: null,
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "meadow fresh milk standard original",
          barcode: "94155006",
          variety: "standard original",
          brand: "meadow fresh",
          slug: "meadow-fresh-milk-standard-original",
          sku: "282793",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 4.87,
            salePrice: 4.87,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282793.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282793.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 2.44,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "2L",
          },
          hasShopperNotes: null,
          productTag: null,
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "anchor milk lite 98.5% fat free",
          barcode: "94160512",
          variety: "lite 98.5% fat free",
          brand: "anchor",
          slug: "anchor-milk-lite-98-5-fat-free",
          sku: "282843",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 4.92,
            salePrice: 4.92,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282843.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282843.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 2.46,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "2L",
          },
          hasShopperNotes: null,
          productTag: null,
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "anchor calci+ milk trim",
          barcode: "94141009",
          variety: "trim",
          brand: "anchor calci+",
          slug: "anchor-calci-milk-trim",
          sku: "282827",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 5.88,
            salePrice: 5.88,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282827.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282827.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 2.94,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "2L",
          },
          hasShopperNotes: null,
          productTag: null,
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "anchor zero-lacto milk standard blue",
          barcode: "94148404",
          variety: "standard blue",
          brand: "anchor zero-lacto",
          slug: "anchor-zero-lacto-milk-standard-blue",
          sku: "708238",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 4.68,
            salePrice: 4.68,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/708238.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/708238.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 4.68,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: null,
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk enriched",
          barcode: "9400597029377",
          variety: "enriched",
          brand: "countdown",
          slug: "countdown-milk-enriched",
          sku: "61661",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 3.02,
            salePrice: 3.02,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/61661.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/61661.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 3.02,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "Other",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: {
              name: "Countdown's Own",
              link: "/shop/productgroup/80842",
              imagePath: "/Content/PromotionTags/F18-Core-Tag.png",
              linkTarget: "_self",
              altText: null,
            },
            targetedOffer: null,
          },
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "meadow fresh milk original uht",
          barcode: "9414090291957",
          variety: "original uht",
          brand: "meadow fresh",
          slug: "meadow-fresh-milk-original-uht",
          sku: "701783",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 1.25,
            salePrice: 1.25,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/701783.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/701783.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 0.5,
            cupMeasure: "100mL",
            packageType: "carton",
            volumeSize: "250mL",
          },
          hasShopperNotes: null,
          productTag: null,
          departments: [
            {
              id: 7,
              name: "Pantry",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "free from lactose milk full cream",
          barcode: "9300633785529",
          variety: "full cream",
          brand: "free from lactose",
          slug: "free-from-lactose-milk-full-cream",
          sku: "799811",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 3.5,
            salePrice: 3.5,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/799811.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/799811.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 0.35,
            cupMeasure: "100mL",
            packageType: "carton",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "IsGreatPrice",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: null,
            targetedOffer: null,
          },
          departments: [
            {
              id: 9,
              name: "Drinks",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "countdown milk skim powder",
          barcode: "9300633765712",
          variety: "skim powder",
          brand: "countdown",
          slug: "countdown-milk-skim-powder",
          sku: "789358",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 12.7,
            salePrice: 12.7,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/789358.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/789358.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 1.27,
            cupMeasure: "100g",
            packageType: "bag",
            volumeSize: "1kg",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "IsGreatPrice",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: null,
            targetedOffer: null,
          },
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "anchor milk standard blue",
          barcode: "94127317",
          variety: "standard blue",
          brand: "anchor",
          slug: "anchor-milk-standard-blue",
          sku: "282848",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 3.03,
            salePrice: 3.03,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282848.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282848.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 3.03,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: null,
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "free from lactose milk lite uht",
          barcode: "9300633785536",
          variety: "lite uht",
          brand: "free from lactose",
          slug: "free-from-lactose-milk-lite-uht",
          sku: "799813",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 3.5,
            salePrice: 3.5,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/799813.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/799813.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 0.35,
            cupMeasure: "100mL",
            packageType: "carton",
            volumeSize: "1L",
          },
          hasShopperNotes: null,
          productTag: {
            tagType: "IsGreatPrice",
            multiBuy: null,
            bonusPoints: null,
            additionalTag: null,
            targetedOffer: null,
          },
          departments: [
            {
              id: 9,
              name: "Drinks",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
        {
          type: "Product",
          name: "fresha valley milk standard a2",
          barcode: "9415724200406",
          variety: "standard a2",
          brand: "fresha valley",
          slug: "fresha-valley-milk-standard-a2",
          sku: "282801",
          unit: "Each",
          selectedPurchasingUnit: null,
          price: {
            originalPrice: 6,
            salePrice: 6,
            savePrice: 0,
            savePercentage: 0,
            hasBonusPoints: false,
            isClubPrice: false,
            isSpecial: false,
            isNew: false,
            canShowOriginalPrice: true,
            discount: null,
            total: null,
            isTargetedOffer: false,
            averagePricePerSingleUnit: null,
            purchasingUnitPrice: null,
            orderedPrice: null,
            isUsingOrderedPrice: false,
            currentPricingMatchesOrderedPricing: null,
            extendedListPrice: null,
            originalAveragePricePerSingleUnit: null,
          },
          images: {
            small:
              "https://assets.woolworths.com.au/images/2010/282801.jpg?impolicy=wowcdxwbjbx&w=65&h=65",
            big: "https://assets.woolworths.com.au/images/2010/282801.jpg?impolicy=wowcdxwbjbx&w=200&h=200",
          },
          quantity: {
            min: 1,
            max: 100,
            increment: 1,
            value: null,
            quantityInOrder: null,
            purchasingQuantityString: null,
          },
          stockLevel: 3,
          eachUnitQuantity: null,
          averageWeightPerUnit: null,
          size: {
            cupPrice: 3,
            cupMeasure: "1L",
            packageType: "bottle",
            volumeSize: "2L",
          },
          hasShopperNotes: null,
          productTag: null,
          departments: [
            {
              id: 4,
              name: "Fridge & Deli",
            },
          ],
          subsAllowed: false,
          supportsBothEachAndKgPricing: false,
          adId: null,
          brandSuggestionId: null,
          brandSuggestionName: null,
          priceUnitLabel: null,
          availabilityStatus: "In Stock",
          onlineSample: null,
          onlineSampleRealProductMapId: 0,
        },
      ],
      totalItems: 634,
    },
    dasFacets: [
      {
        key: "Department",
        value: "4",
        isBooleanValue: false,
        name: "Fridge & Deli",
        productCount: 218,
        shelfResponses: null,
        group: "Department",
      },
      {
        key: "Department",
        value: "5",
        isBooleanValue: false,
        name: "Bakery",
        productCount: 1,
        shelfResponses: null,
        group: "Department",
      },
      {
        key: "Department",
        value: "6",
        isBooleanValue: false,
        name: "Frozen",
        productCount: 10,
        shelfResponses: null,
        group: "Department",
      },
      {
        key: "Department",
        value: "7",
        isBooleanValue: false,
        name: "Pantry",
        productCount: 239,
        shelfResponses: null,
        group: "Department",
      },
      {
        key: "Department",
        value: "9",
        isBooleanValue: false,
        name: "Drinks",
        productCount: 459,
        shelfResponses: null,
        group: "Department",
      },
      {
        key: "Department",
        value: "10",
        isBooleanValue: false,
        name: "Health & Body",
        productCount: 35,
        shelfResponses: null,
        group: "Department",
      },
      {
        key: "Department",
        value: "11",
        isBooleanValue: false,
        name: "Household",
        productCount: 2,
        shelfResponses: null,
        group: "Department",
      },
      {
        key: "Department",
        value: "12",
        isBooleanValue: false,
        name: "Baby & Child",
        productCount: 21,
        shelfResponses: null,
        group: "Department",
      },
      {
        key: "Department",
        value: "13",
        isBooleanValue: false,
        name: "Pet",
        productCount: 48,
        shelfResponses: null,
        group: "Department",
      },
      {
        key: "Department",
        value: "15",
        isBooleanValue: false,
        name: "Halloween",
        productCount: 13,
        shelfResponses: null,
        group: "Department",
      },
      {
        key: "Department",
        value: "16",
        isBooleanValue: false,
        name: "Christmas",
        productCount: 100,
        shelfResponses: null,
        group: "Department",
      },
    ],
    facets: [
      {
        key: "All",
        value: "All",
        isBooleanValue: true,
        name: "All",
        productCount: 241,
        shelfResponses: null,
        group: "Specials & Great Prices",
      },
      {
        key: "Special",
        value: "Special",
        isBooleanValue: true,
        name: "Special",
        productCount: 180,
        shelfResponses: null,
        group: "Specials & Great Prices",
      },
      {
        key: "Great Price",
        value: "Great Price",
        isBooleanValue: true,
        name: "Great Price",
        productCount: 61,
        shelfResponses: null,
        group: "Specials & Great Prices",
      },
      {
        key: "Onecard Club",
        value: "Onecard Club",
        isBooleanValue: true,
        name: "Onecard Club",
        productCount: 57,
        shelfResponses: null,
        group: "Specials & Great Prices",
      },
      {
        key: "PiesAttributes",
        value: "Dairy Free",
        isBooleanValue: false,
        name: "Dairy Free",
        productCount: 200,
        shelfResponses: null,
        group: "Dietary & Lifestyle",
      },
      {
        key: "PiesAttributes",
        value: "Gluten Free",
        isBooleanValue: false,
        name: "Gluten Free",
        productCount: 339,
        shelfResponses: null,
        group: "Dietary & Lifestyle",
      },
      {
        key: "PiesAttributes",
        value: "Low Salt",
        isBooleanValue: false,
        name: "Low Salt",
        productCount: 329,
        shelfResponses: null,
        group: "Dietary & Lifestyle",
      },
      {
        key: "PiesAttributes",
        value: "Low Sugar",
        isBooleanValue: false,
        name: "Low Sugar",
        productCount: 208,
        shelfResponses: null,
        group: "Dietary & Lifestyle",
      },
      {
        key: "PiesAttributes",
        value: "Organic",
        isBooleanValue: false,
        name: "Organic",
        productCount: 45,
        shelfResponses: null,
        group: "Dietary & Lifestyle",
      },
      {
        key: "PiesAttributes",
        value: "Vegan",
        isBooleanValue: false,
        name: "Vegan",
        productCount: 182,
        shelfResponses: null,
        group: "Dietary & Lifestyle",
      },
      {
        key: "PiesAttributes",
        value: "Vegetarian",
        isBooleanValue: false,
        name: "Vegetarian",
        productCount: 343,
        shelfResponses: null,
        group: "Dietary & Lifestyle",
      },
    ],
    sortOptions: [
      {
        value: "Relevance",
        text: "Relevance",
        selected: true,
      },
      {
        value: "Aisle",
        text: "Aisle",
        selected: false,
      },
      {
        value: "PriceAsc",
        text: "Price Low to High",
        selected: false,
      },
      {
        value: "PriceDesc",
        text: "Price High to Low",
        selected: false,
      },
      {
        value: "CUPAsc",
        text: "Unit Price Low to High",
        selected: false,
      },
    ],
    currentPageSize: 24,
    currentSortOption: "Relevance",
    brandSuggestions: null,
    breadcrumb: {
      department: null,
      aisle: null,
      shelf: null,
      productGroup: null,
      dynamicGroup: null,
    },
    partialFailures: {
      shopperNotesFetchFailed: null,
      maxSupplyLimitFetchFailed: null,
      purchaseUnitFetchFailed: null,
      trolleyQuantityUpdateFailed: null,
      productTagFetchFailed: null,
      breadcrumbGenerationFailed: null,
      productGroupFetchFailed: null,
      targetOfferFetchFailed: null,
    },
    targetedOfferDetails: null,
    action: null,
    isSuccessful: true,
    rootUrl: "http://shop.countdown.co.nz",
    context: {
      shopper: {
        firstName: null,
        isShopper: false,
        isLoggedIn: false,
        hasOnecard: false,
        oneCardBalance: null,
        shopperIdHash: null,
        shopperScvId: "",
        sessionGroups: null,
        orderCount: null,
        isSupplyLimitOverrideShopper: false,
        isPriorityShopper: false,
        isChangingOrder: false,
        changingOrderId: null,
        hasActiveDeliverySubscription: false,
      },
      fulfilment: {
        address: "Glenfield",
        selectedDate: null,
        selectedDateWithTZInfo: null,
        startTime: null,
        endTime: null,
        method: "Courier",
        cutOffTime: null,
        isSlotToday: false,
        isAddressInDeliveryZone: true,
        isDefaultDeliveryAddress: false,
        areaId: 77,
        suburbId: 0,
        pickupAddressId: 0,
        fulfilmentStoreId: 9443,
        perishableCode: "P",
        locker: null,
        expressFulfilment: {
          isExpressSlot: false,
          expressPickUpFee: null,
          expressDeliveryFee: null,
        },
      },
      enabledFeatures: [
        "HaveYouForgotten",
        "ProjectShore",
        "ManagedServiceBar",
        "RecipesAddToTrolley",
        "SavedRecipes",
        "ProductStraps",
        "DeliverySubscriptionSignUp",
        "FirstTimeShopper",
        "OrderConfirmation",
        "NewDeliverySubscriptionPage",
        "CancelOrder",
        "CountryOfOriginInAccordion",
        "PiesEnableEachUnitForKgProducts",
        "ForgotPassword",
        "JQueryDeprecationLogging",
        "PaperPackingSlipPreference",
        "EnableDeliverySaverRetryPayment",
        "RecipesInApp",
        "DeliverySaverBannerOnTrolleyPage",
        "RecipeCategorySeo",
        "EnableBoostsLandingPage",
        "CustomerSelfService",
        "MerchantHostedLocalStorefront",
        "AccountMenuMyOrdersLink",
        "HideTargetedCategoryOffersBanner",
        "TargetedCategoryOffers",
        "LazyLoadProductStampImages",
        "OptimizelyWeb",
        "ChangeOrderAccountMenu",
        "ChangeOrderPromptHomepage",
        "ChangeOrder",
        "ChangeOrderIndicateChangedPriceInProductList",
        "SwitchToggleToShowInStockItemsOnly",
        "HideSwitchToggleForOOS",
        "ExpressDelivery",
        "ExpressPickup",
        "Optimizely",
        "PromotionTilesInBrowseMegaMenu",
        "NewOrderConfirmationPage",
        "StickyCTAReviewOrder",
        "ViewOrderConfirmationLinkOnMyOrders",
        "ChangeOrderChangedPriceTutorial",
        "OnlineSamplesCheckoutJourney",
        "OnlineSampleOrderConfirmation",
        "ShowDiscountPercentage",
        "GreatToLowPrice",
        "OnlineSampleRemarketing",
        "DynamicPromoTilesInBrowseMegaMenu",
      ],
      shoppingListItems: [],
      basketTotals: null,
      advancedSettingsResponse: null,
    },
    messages: null,
  },
];
